/* Verilog module instantiation template generated by SCUBA Diamond (64-bit) 3.14.0.75.2 */
/* Module Version: 5.7 */
/* Wed Oct 29 19:00:15 2025 */

/* parameterized module instance */
pll_24m __ (.CLKI( ), .CLKOP( ), .CLKOS( ));
