// Generated by training/box20/train_box20.py
localparam integer BOX20_C1 = 32;
localparam integer BOX20_IN_CH = 3;
localparam integer BOX20_W = 20;
localparam integer BOX20_H = 20;
localparam integer BOX20_SHIFT1 = 7;
localparam integer BOX20_SHIFT_FC = 7;
localparam [7:0] BOX20_THRESHOLD = 8'd160;
