/* Verilog module instantiation template generated by SCUBA Diamond (64-bit) 3.14.0.75.2 */
/* Module Version: 5.7 */
/* Fri Mar 06 02:32:50 2026 */

/* parameterized module instance */
PLL __ (.CLKI( ), .CLKOP( ), .CLKOS( ));
