' ----------------------------------------------
' Script generated by SIwave
' Thu Feb  5 08:03:34 2026
' ----------------------------------------------
Dim oAnsoftApp
Dim oDesktop
Dim oProjects
Dim oProject
Dim projectPath
Dim oFSO
Dim oTextFile
Set oAnsoftApp = CreateObject("Ansoft.ElectronicsDesktop.2025.2")
Set oDesktop = oAnsoftApp.GetAppDesktop()
oDesktop.RestoreWindow

Set oProjects = oDesktop.GetProjects
For Each oProject in oProjects
  projectPath = oProject.GetPath() + oProject.GetName()
  If projectPath = "C:/Users/kunshpreetbaweja/github/AiCamera/siwave/main.siwaveresults/Designer/SIwizard1_schematic" Then
    Set oFSO = CreateObject("Scripting.FileSystemObject")
    Set oTextFile = oFSO.CreateTextFile("C:/Users/kunshpreetbaweja/github/AiCamera/siwave/main.siwaveresults/Designer/AEDTProjectAlreadyOpen.tmp", True)
    oTextFile.Close
    Exit For
  End If
Next
