/* Verilog module instantiation template generated by SCUBA Diamond (64-bit) 3.14.0.75.2 */
/* Module Version: 5.7 */
/* Wed Oct 29 00:41:38 2025 */

/* parameterized module instance */
pll24m_to_48m __ (.CLKI( ), .CLKOP( ));
